# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        name: Remove trailing whitespace
        description: This hook removes trailing whitespace from all types of files.
      - id: end-of-file-fixer
        name: Fix end of files
        description: Ensures that a file is either empty, or ends with one newline.
      - id: mixed-line-ending
        name: Fix mixed line endings
        description: Replaces or checks mixed line ending types.
        args: [--fix=lf]
      - id: check-merge-conflict
        name: Check for merge conflicts
        description: Check for files that contain merge conflict strings.
      - id: check-case-conflict
        name: Check for case conflicts
        description: Check for files that would conflict in case-insensitive filesystems.
